spring:
  application:
    name: inventory-service
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:fleet-kafka-kafka-bootstrap:9092}
    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

logging:
  level:
    com.fleet.inventory: INFO
    org.springframework.kafka: INFO