replicas: 1
service:
  type: LoadBalancer
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
postgresql:
  enabled: false
extraEnv: |
  - name: KEYCLOAK_USER
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: admin123
http:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
