apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-notification-service
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  
  source:
    repoURL: https://github.com/chrisjamaica91/k8s-fleet-management
    targetRevision: main
    path: kustomize/overlays/dev/notification-service
  
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true